name: test

on:
  workflow_dispatch:
    inputs:
      url:
        required: true
      
env:
  URL: ${{ github.event.inputs.url }}

jobs:
  FCE:    
    runs-on: ubuntu-latest

    steps:  
      - uses: actions/checkout@v4  

      - name: cache  
        id: cache  
        uses: actions/cache@v4  
        with:  
          path: |  
            ~/.local/lib/python3*/site-packages  
            tools  
          key: ${{ runner.os }}-cache-${{ hashFiles('**/tools/*') }}  
          restore-keys: |  
            ${{ runner.os }}-cache-  

      - name: install  
        if: steps.cache.outputs.cache-hit != 'true'  
        run: |  
          if [ ! -d tools ]; then  
            sudo apt-get update && sudo apt-get install -y python3-pip p7zip-full aria2  
            git clone https://github.com/vm03/payload_dumper.git tools  
            aria2c -o erofs-utils.zip https://github.com/sekaiacg/erofs-utils/releases/download/v1.8.1-240810/erofs-utils-v1.8.1-gddbed144-Linux_x86_64-2408101422.zip  
            7z x erofs-utils.zip -otools  
            pip install -r ./tools/requirements.txt  
            rm -f erofs-utils.zip  
          fi  

      - name: download  
        run: |  
          aria2c -x 7 -s 7 -k 1M --continue --max-tries=0 --log=LOG --out='exrom.zip' "$URL"  
          7z x exrom.zip -o./  
          rm exrom.zip  

      - name: EC  
        run: |
          ./tools/payload_dumper.py payload.bin --out extracted --images boot,recovery,vendor_boot,dsp,odm,vendor_dlkm,dtbo,imagefv,tz,uefi,bluetooth,hyp,xbl,xbl_ramdump,keymaster,aop,abl,uefisecapp,cpucp,xbl_config,featenabler,shrm,qupfw,devcfg,aop_config,vbmeta,vbmeta_system

      - name: List Extracted Files
        run: |
          echo "Extracted files in 'extracted' directory:"
          ls -l extracted/